name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy on VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            IMAGE_ID="ghcr.io/${{ github.repository }}"
            IMAGE_ID_LOWER=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')

            echo "Pulling image: $IMAGE_ID_LOWER:latest"
            docker pull "$IMAGE_ID_LOWER:latest"

            echo "Stopping and removing existing container if any"
            docker stop myapp || true
            docker rm myapp || true

            echo "Running container"
            docker run -d \
              --name myapp \
              -p 80:8080 \
              --restart unless-stopped \
              "$IMAGE_ID_LOWER:latest"
