name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH & Deploy on VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop any existing container (optional)
            docker stop myapp || true
            docker rm myapp || true

            # Run container with restart policy
            docker run -d \
              --name myapp \
              -p 80:8080 \
              --restart unless-stopped \
              ghcr.io/${{ github.repository }}:latest
