name: CI Pipeline

on:
  push:
    branches:
      - '**'
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install pytest  # Ensure pytest is installed for tests

      - name: Run tests
        run: |
          python -m pytest  # Corrected command to run pytest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID_LOWER=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          docker build -t "$IMAGE_ID_LOWER:latest" .

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID_LOWER=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          docker push "$IMAGE_ID_LOWER:latest"
